### ISSUE TITLE
Updating on blender

### ISSUE THREAD

**Issue by ArtofSteelio** [TrueCryer/blendermada_client#13]
After installing Blendermada, everything is normal until I updated the Blendermada materials for the first time. The main categories are showing on the left but the subcategories on the right aren't showing up. It doesn't allow me to use the materials. please help.

**Comment by TrueCryer** [comment]
I think your problem is based on wrong render engine. Client shows only materials for current render engine, but all available categories. By default Blender chooses "Blender Render", and Blendermada has only three materials for it, unfortunately.

So change render engine to Cycles and press update - you will see much more.
